language: node_js
node_js:
 - "node"
script:
 - npm test
 - npm run build
cache: npm
#before_deploy: "npm run build"
deploy:
  provider: npm
  skip_cleanup: true
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    branch: master
